#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

if [[ -z "$FLATPAK_ID" ]]; then
    if [[ -d /nix ]]; then
        nix-shell --command "npx lint-staged"
        nix-shell --command "npx prettier -c ."
    else
        npx lint-staged
        npx prettier -c .
    fi
else
    exec flatpak-spawn --host --env=TERM=xterm-256color $0 $@
fi